### ISSUE TITLE
A strange error in the transform class： 'tuple' object is not callable

### ISSUE THREAD

**Issue by Asamisora** [PatrickHua/SimSiam#10]
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    main(args=get_args())
  File "main.py", line 68, in main
    for idx, ((images1, images2), _) in enumerate(p_bar):
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 272, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 120, in __getitem__
    img = self.transform(img)
  File "/mnt/users/03_simsiam/augmentations/simsiam_aug.py", line 25, in __call__
    x1 = self.transform(x)
  File "/mnt/users/miniconda3/envs/simsiam/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 68, in __call__
    img = t(img)
TypeError: 'tuple' object is not callable

-------------------------------------------------------------------------------------------
I met this TypeError when I run the commad:
python main.py --debug --dataset cifar10 --data_dir my/data/folder/ --output_dir ./outputs
And I print the type of x in the code ' x1 = self.transform(x)' ,which may cause this error :
<class 'PIL.Image.Image'>

**Comment by Asamisora** [comment]
All, right. I find the latest update have solved this issue. Thank you so much!

**Comment by SooDevv** [comment]
@Asamisora how do you fix it?

**Comment by Asamisora** [comment]
> @Asamisora how do you fix it?

I pull the latest version of code, then no more this issue.
