### ISSUE TITLE
--resume not implemented

### ISSUE THREAD

**Issue by leodesigner** [PatrickHua/SimSiam#15]
Need to resume training.
Followed example in linear_eval.py

but getting:
```
Resuming model from outputs/custom_small_resnet18/simsiam-custom_small-epoch300.pth
Epoch 0/500:   0%|                                                                                                                                   | 0/1263 [00:02<?, ?it/s]
Training:   0%|                                                                                                                                       | 0/500 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    main(args=get_args())
  File "main.py", line 101, in main
    loss = model.forward(images1.to(args.device), images2.to(args.device))
TypeError: forward() takes 2 positional arguments but 3 were given
```

How to properly load checkpoint and resume training ?
Thanks !

**Comment by PatrickHua** [comment]
Will add resume tomorrow!

**Comment by leodesigner** [comment]
I see model is wrapped for multi GPU training, can you provide hint how to load it back to resume training ?
Thanks.
